{% set name = "httpx" %}
{% set version = "0.23.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 202ae15319be24efe9a8bd4ed4360e68fde7b38bcc2ce87088d416f026667d19

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - httpx=httpx:main

requirements:
  host:
    - python >=3.8
    - hatchling
    - hatch-fancy-pypi-readme
    - pip
  run:
    - python >=3.8
    - certifi
    - sniffio
    - httpcore >=0.15.0,<0.17.0
    - idna
    - rfc3986 >=1.3,<2


test:
  imports:
    - httpx
  requires:
    - click ==8.*
    - pip
    - pygments ==2.*
    - rich >=10,<13
  commands:
    - pip check
    - httpx --help

about:
  home: https://github.com/encode/httpx
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: A next-generation HTTP client for Python.
  doc_url: https://www.encode.io/httpx/
  dev_url: https://github.com/encode/httpx

extra:
  recipe-maintainers:
    - primozgodec
    - florimondmanca
    - thewchan
